# Generated by Django 3.2.12 on 2022-05-11 18:14

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('Proper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='image',
            field=models.ImageField(blank=sqlalchemy.sql.expression.true, max_length=500, null=sqlalchemy.sql.expression.true, upload_to=''),
        ),
    ]
