# Generated by Django 3.2.12 on 2022-05-11 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proper', '0002_alter_mineral_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bought_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proper.seller')),
            ],
        ),
    ]
