# Generated by Django 3.2.12 on 2022-05-11 18:40

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('Proper', '0003_auto_20220511_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='amount',
            field=models.IntegerField(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='seller',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
