# Generated by Django 3.2.12 on 2022-05-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proper', '0004_auto_20220511_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
