# Generated by Django 3.2.12 on 2022-05-12 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proper', '0005_alter_mineral_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='bought_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proper.seller'),
        ),
    ]
