# Generated by Django 3.2.12 on 2022-05-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proper', '0006_auto_20220512_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='price',
            field=models.IntegerField(),
        ),
    ]
